# Generated by Django 3.2.20 on 2023-09-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accident', '0002_accident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
