# Generated by Django 3.2.21 on 2023-09-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accident', '0003_alter_accident_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fecility',
            old_name='feciity_type',
            new_name='feciities',
        ),
    ]
