# Generated by Django 3.2.21 on 2023-09-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accident', '0004_rename_feciity_type_fecility_feciities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fecility',
            old_name='feciities',
            new_name='feciity_type',
        ),
    ]
